name: Build, test and publish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_local:
    name: Build and publish local
    if: github.repository_owner == 'ParadoxGameConverters'
    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: "Get previous tag"
      if: ${{ github.event_name == 'push' }}
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
    - name: "Build converter sln"
      run: |
       cd "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\"
       .\MSBuild.exe -m -p:Configuration=Release $Env:GITHUB_WORKSPACE\ImperatorToCK2.sln -target:ImperatorToCK2

    - name: "Build converter executable"
      run: |
       cd $Env:GITHUB_WORKSPACE\ImperatorToCk2
       mvn -e -X clean verify

    - name: "Copy backend to Release directory"
      run: |
       mv ImperatorToCk2/target/jpackage/ImperatorToCK2 Release/ImperatorToCK2
      
    - name: "Build frontend"
      uses: ./Fronter.NET/.github/actions/build_frontend
      with:
        fronter_dir: 'Fronter.NET'
        release_dir: 'Release'
       
    - name: "Prepare release"
      if: ${{ github.event_name == 'push' }}
      run: |
       cd "C:\Program Files\7-Zip\"
       .\7z.exe a $Env:GITHUB_WORKSPACE\ImperatorToCk2-testing.zip $Env:GITHUB_WORKSPACE\Release\*
       
    - name: "Upload binaries to release"
      if: ${{ github.event_name == 'push' }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.previoustag.outputs.tag }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        artifacts: ImperatorToCk2-testing.zip
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: "Cleanup"
      if: always()
      run: |
        Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Force | Remove-Item -force -recurse

  build_foreign:
    name: Build foreign
    if: github.repository_owner != 'ParadoxGameConverters'
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: "Build converter sln"
      run: |
       cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
       .\MSBuild.exe -m -p:Configuration=Release $Env:GITHUB_WORKSPACE\ImperatorToCK2.sln -target:ImperatorToCK2

    - name: "Build converter jar"
      run: |
       cd $Env:GITHUB_WORKSPACE\ImperatorToCk2
       mvn package

    - name: "Install launch4j"
      run: |
       cd $Env:GITHUB_WORKSPACE\Release
       curl -L -o launch4j.zip https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-win32.zip/download
       7z x launch4j.zip
       rm launch4j.zip
       mv launch4j-3.14-win32 launch4j
       cd launch4j
       .\launch4j.exe -help

    - name: "Convert jar to executable"
      working-directory: ImperatorToCK2
      run: |
       ../launch4j/launch4jc.exe launch4j_config.xml

    - name: "Copy backend executable to Release directory"
      run: |
       cp ImperatorToCK2/ImperatorToCK2.exe Release/ImperatorToCK2
      
    - name: "Build frontend"
      uses: ./Fronter.NET/.github/actions/build_frontend
      with:
        fronter_dir: 'Fronter.NET'
        release_dir: 'Release'
